{{- define "argus.secret" -}}
{{- if .Values.secret.create }}
---
{{ $secretName := .Values.secret.name | default (include "bjw-s.common.lib.chart.names.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .Values.secret.type }}
{{- with .Values.secret.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.secret.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
