apiVersion: v2
name: wud
description: Helm chart for WUD (What's Up Docker)
home: https://github.com/getwud/wud
icon: https://raw.githubusercontent.com/getwud/wud/refs/heads/main/docs/assets/wud-logo.svg
type: application
version: 0.1.0
appVersion: "8.1.1"
kubeVersion: ">=1.28.0-0"
maintainers:
  - name: m0sh1
    email: sm@m0sh1.cc
sources:
  - https://github.com/getwud/wud
keywords:
  - wud
  - whats-up-docker
  - monitoring
  - notifications
dependencies:
  - name: common
    version: 4.5.0
    repository: https://bjw-s-labs.github.io/helm-charts
