apiVersion: v2
name: wud
description: Helm chart for WUD (What's Up Docker)
icon: https://raw.githubusercontent.com/getwud/wud/refs/heads/main/ui/public/img/icons/apple-touch-icon.png
home: https://github.com/getwud/wud
type: application
version: 0.2.0
appVersion: "8.1.1"
kubeVersion: ">=1.28.0-0"
maintainers:
  - name: m0sh1
    email: sm@m0sh1.cc
sources:
  - https://github.com/getwud/wud
keywords:
  - wud
  - whats-up-docker
  - monitoring
  - notifications
dependencies:
  - name: common
    version: 4.6.0
    repository: https://bjw-s-labs.github.io/helm-charts
