repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [ --allow-multiple-documents ]
        exclude: ^(apps/.*/templates/|charts/.*/templates/)
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
        exclude: \.j2$
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - -c
          - .yamllint.yml
        files: \.(yml|yaml)$

  - repo: local
    hooks:
      - id: helm-lint
        name: helm lint (changed charts)
        entry: .ci/pre-commit/helm-lint.sh
        language: system
        pass_filenames: false
        files: ^charts/

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 42.74.2
    hooks:
      - id: renovate-config-validator
        args: [ --strict ]
