apiVersion: v2
name: homepage
description: Helm chart for Homepage dashboard
icon: https://raw.githubusercontent.com/gethomepage/homepage/main/public/mstile-150x150.png
type: application
version: 0.3.0
appVersion: "v1.8.0"
kubeVersion: ">=1.28.0-0"
maintainers:
  - name: m0sh1
    email: sm@m0sh1.cc

home: https://github.com/gethomepage/homepage
sources:
  - https://github.com/gethomepage/homepage
  - https://github.com/bjw-s-labs/helm-charts

dependencies:
  - name: common
    version: 4.6.0
    repository: https://bjw-s-labs.github.io/helm-charts
