apiVersion: v2
name: homepage
description: Helm chart for Homepage dashboard
icon: https://github.com/gethomepage/homepage/blob/main/public/mstile-150x150.png
type: application
version: 0.1.1
appVersion: "v1.8.0"
kubeVersion: ">=1.28.0-0"

home: https://github.com/gethomepage/homepage
sources:
  - https://github.com/gethomepage/homepage
  - https://github.com/bjw-s-labs/helm-charts

dependencies:
  - name: common
    version: 4.5.0
    repository: https://bjw-s-labs.github.io/helm-charts
