apiVersion: v2
name: cyberchef
description: Helm chart for CyberChef
icon: https://github.com/gchq/CyberChef.png
home: https://github.com/gchq/CyberChef
type: application
version: 0.1.1
appVersion: "v10.19.4"
kubeVersion: ">=1.28.0-0"
maintainers:
  - name: m0sh1
    email: sm@m0sh1.cc
sources:
  - https://github.com/gchq/CyberChef
keywords:
  - cyberchef
  - gchq
  - utilities
dependencies:
  - name: common
    version: 4.5.0
    repository: https://bjw-s-labs.github.io/helm-charts
