apiVersion: v2
name: it-tools
description: Helm chart for IT-Tools
icon: https://raw.githubusercontent.com/CorentinTh/it-tools/main/.github/logo-dark.png
type: application
version: 0.1.0
appVersion: "2024.10.22-7ca5933"
kubeVersion: ">=1.28.0-0"
maintainers:
  - name: m0sh1
    email: sm@m0sh1.cc
home: https://it-tools.tech
sources:
  - https://github.com/CorentinTh/it-tools
  - https://github.com/bjw-s-labs/helm-charts
keywords:
  - it-tools
  - utilities
  - dashboard

dependencies:
  - name: common
    version: 4.5.0
    repository: https://bjw-s-labs.github.io/helm-charts
