apiVersion: v2
name: argus
description: Helm chart for Release-Argus
icon: https://github.com/release-argus/Argus/raw/master/web/ui/react-app/public/favicon.svg
home: https://release-argus.io
type: application
version: 0.3.0
appVersion: "0.29.0"
kubeVersion: ">=1.28.0-0"
maintainers:
  - name: m0sh1
    email: sm@m0sh1.cc
sources:
  - https://github.com/release-argus/Argus
keywords:
  - argus
  - releases
  - notifications
  - monitoring
dependencies:
  - name: common
    version: 4.5.0
    repository: https://bjw-s-labs.github.io/helm-charts
