controllers:
  main:
    containers:
      main:
        image:
          repository: releaseargus/argus
          tag: "0.29.0"
          pullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env: []
        envFrom: []
        resources: {}

service:
  main:
    controller: main
    ports:
      http:
        port: 8080
        primary: true

ingress:
  main:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: argus.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls: []

serviceAccount:
  argus:
    enabled: false
    annotations: {}
    labels: {}
    # forceRename: ""

podAnnotations: {}
podLabels: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

config:
  useExistingConfigMap: ""
  filename: config.yml
  mountPath: /config
  # Optional: load the service block from a separate file/string
  # Use --set-file config.serviceFromFile=path/to/services.yaml
  serviceFromFile: ""
  autoIcons:
    enabled: false
    github: true
    webFavicon: true
  data:
    settings:
      web:
        listen_addr: 0.0.0.0
        listen_port: 8080
    service: {}
  raw: ""

secret:
  create: false
  name: ""
  existingSecret: ""
  envFrom: false
  annotations: {}
  labels: {}
  type: Opaque
  stringData: {}
  data: {}

persistence: {}
