apiVersion: v2
name: gitea-runner
description: Helm chart for Gitea Actions runner with optional Docker-in-Docker
icon: https://github.com/go-gitea.png
home: https://gitea.com/gitea/act_runner
type: application
version: 0.2.0
appVersion: "0.2.13"
kubeVersion: ">=1.28.0-0"
maintainers:
  - name: m0sh1
    email: sm@m0sh1.cc
sources:
  - https://gitea.com/gitea/act_runner
keywords:
  - gitea
  - actions
  - runner
  - ci
dependencies:
  - name: common
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts
